AWSTemplateFormatVersion: '2010-09-09'
Description: 'Supplemental resources for CodeDeploy ECS Blue/Green deployments: S3 artifacts bucket, TG green, CloudWatch alarm, and SNS topic.'

Resources:
  # ✅ S3 Bucket for CodeDeploy artifacts
  CodeDeployArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kesseh-galleries-codedeploy-artifacts
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30

  # ✅ Green Target Group (for use in CodeDeploy blue/green)
  TargetGroupGreen:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: kesseh-galleries-tg-green
      Protocol: HTTP
      Port: 80
      TargetType: ip
      VpcId: vpc-02adc195cf286713a  # ✅ Update this if your VPC ID changes
      HealthCheckPath: /api/tg/health
      HealthCheckProtocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "300"

  # ✅ CloudWatch Alarm (used for rollback monitoring)
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: kesseh-galleries-high-error-rate
      AlarmDescription: High error rate detected on green target group
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TargetGroup
          Value: !Sub 'targetgroup/${TargetGroupGreen}/*'

  # ✅ SNS Topic for deployment notifications
  DeploymentNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: kesseh-galleries-deployment-notifications
      DisplayName: Kesseh Galleries Deployment Notifications

Outputs:
  ArtifactsBucket:
    Description: S3 Bucket for CodeDeploy artifacts
    Value: !Ref CodeDeployArtifactsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactsBucket'

  TargetGroupGreenOutput:
    Description: Green target group for ECS Blue/Green deployments
    Value: !Ref TargetGroupGreen
    Export:
      Name: !Sub '${AWS::StackName}-TargetGroupGreen'

  HighErrorRateAlarm:
    Description: CloudWatch Alarm for monitoring 5XX errors
    Value: !Ref HighErrorRateAlarm
    Export:
      Name: !Sub '${AWS::StackName}-HighErrorRateAlarm'

  DeploymentNotificationTopic:
    Description: SNS Topic for deployment notifications
    Value: !Ref DeploymentNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-DeploymentNotificationTopic'